services:
  - type: web
    name: spss-syntax-generator
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn backend_app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    healthCheckPath: /api/health
